### PR TITLE
Multilingual support and other changes

### PR DESCRIPTION
**Pull request by mentaljam**
Hi!
Here is the multilingual support and my Russian translation.

### CODE REVIEW

**Comment by cornedor** [comment]
Thanks, I'll try to look at it this evening.

**Comment by mentaljam** [comment]
Hi!
Here is some new commits. Maybe you will find them useful)

**Comment by cornedor** [comment]
Thanks, have you tested everything? I've lost access to my phone :( haven't used it in a long time and forgot my pin code.

**Comment by mentaljam** [comment]
I have but you know how it happens...

**Comment by mentaljam** [comment]
Here are fixes for my previous commits and some new features:
 - recursive search for recordings
 - better file system watching
 - simple picker for recordings location

**Comment by cornedor** [comment]
Thanks for all the commits, I'll try to push an update to the store this weekend.

**Comment by mentaljam** [comment]
Hi,
If you don't mind I can publish a forked version on the OpenRepos.

**Comment by cornedor** [comment]
Yes i'm fine with that, I can also add you to this repo and upload RPM's to harbour if you want?

Could you send me a link when you've uploaded it to OpenRepos, I'll will change mine and link to your's

**Comment by mentaljam** [comment]
Ok thanks!

**Comment by mentaljam** [comment]
Here is the link to OpenRepos https://openrepos.net/content/osetr/recorder-fork

> I can also add you to this repo and upload RPM's to harbour if you want?

I think it's good to wait for some issue reports from OpenRepos.

**Comment by cornedor** [comment]
Thanks, I've changed my entry on openrepos.

**Comment by mentaljam** [comment]
Hi,
Currently there are more than 500 downloads from OpenRepos with no issue reports. So I think the last version could be uploaded to Harbour.

**Comment by cornedor** [comment]
Awesome, i'll upload it to the harbour store.

Is this the complete changelog?

Version 0.5.2-1

And French translation and update others
Version 0.5.1-1

Add Spanish, Italian and Swedish translations

**Comment by mentaljam** [comment]
If we are speaking about all my commits then it should be something like this (my English could be not so good):

- Add multilingual support (add French, Italian, Russian, Spanish and Swedish translations)
- Show more actions and recording duration label on cover page 
- Block recordings list while recording
- Use native notification API
- Fix packaging rules (do not install unnecessary files)
- A better rename dialogue (show a file name without an extension, add a placeholder text)
- Improve recordings list (an option for a recursive search for recordings which is disabled by default, update recordings view on recordings location changed)
- Set recordings location with a simple directory picker
- Code refactoring

**Comment by cornedor** [comment]
Thanks, I'll upload it tonight.

**Comment by cornedor** [comment]
I've uploaded it to the store

**Comment by cornedor** [comment]
capture

**Pull request merged**
